######################################################################
# Automatically generated by qmake (3.0) Fri Dec 5 11:02:30 2014
######################################################################

TEMPLATE = app
TARGET = vohttpd
INCLUDEPATH += . src

# Input
HEADERS += src/vohttpd.h
SOURCES += src/vohttpd.c \
           src/vohttpdext.c

OTHER_FILES += \
           src/plugins/libvohttpd.plugin.c \
           src/plugins/libvohttpd.test.c
